@startuml
abstract Class Proprietario {
  

    +consultarPedidos();
}

Class Cliente extends Proprietario
{   
    -nome: String
    -endereco: String
    -pedidos: List<Pedido>
    -cpf: String
    -rg: String
    -profissao: String
    -empregadores: Lista<String>
    -salarioTotal: Double
    -pedidos: List<Pedido>

    +realizarCadastro();
    +consultarPedidos();
}

abstract Class Agente extends Proprietario
{
    -CNPJ: String
    -nome: String
    -endereco: String
    -pedidos: List<Pedido>
    -contratos: List<Contrato>
    
    +realizarCadastro();
    +consultarPedidos();
}

Class Empresa extends Agente
{   
    -pedidos: List<Pedido>
    -CNPJ: String
    -nome: String
    -endereco: String
    -contratos: List<Contrato>

    +realizarCadastro();
}

Class Banco extends Agente
{   
    -pedidos: List<Pedido>
    -CNPJ: String
    -nome: String
    -endereco: String
    -contratos: List<Contrato>

    +realizarCadastro();
    +concederCredito()
}

class Pedido 
{
    -id: String
    -status: StatusPedido
    -data: Date
    -cliente: Cliente
    -contrato: Contrato
    
    +adicionarPedido()
    +alterarStatus()
    +modificarPedido()
    +cancelarPedido()
    +avaliarPedido()
}

Enum StatusPedido {
    -ANALISE
    -APROVADO
    -CANCELADO
}

Class Contrato 
{
    -id: String
    -cliente: Cliente
    -agente: Agente
    -tipoDeContrato: TipoDeContrato
    -optouPelaCompra: boolean
    -automovel: Automovel
    +executarContrato()
}

Class Automovel
{   
    -proprietario: Proprietario
    -matricula: String
    -placa: String
    -marca: String
    -modelo: String
    -ano: Date
    +cadastrarAutomovel()
}

Enum TempoDeContrato {
    -12
    -24
    -36
    -48
}

Cliente "1" -- "0..N" Pedido
Pedido "1" -- "0..1" Contrato
Contrato "1..N" -- "1" Agente
Contrato "1" -- "1..N" Automovel

@enduml
