@startuml
package "SistemaLocacao" {
  
  package "Frontend" {
    package "UI" {
      class HomePage
      class CadastroPage
      class PedidoPage
    }

    package "Controllers" {
      class PedidoController
      class UsuarioController
      class AutomovelController
      class ContratoController  
    }
  }

  package "Backend" {
    package "Services" {
      class PedidoService
      class ContratoService
      class UsuarioService
      class AutomovelService
    }

    package "Repositories" {
      class PedidoRepository
      class ContratoRepository
      class UsuarioRepository
      class AutomovelRepository
    }

    package "Models" {
      class Pedido
      class Contrato
      class Cliente
      class Agente
      class Automovel
      class Empresa
      class Banco
    }
  }

  package "Database" {
    class MySQLDatabase
    class PedidoTable
    class ContratoTable
    class ClienteTable
    class AgenteTable
    class AutomovelTable
    class EmpresaTable   
    class BancoTable
  }
}

' Relacionamentos
Frontend.Controllers -- Backend.Services
Backend.Services -- Backend.Repositories
Backend.Repositories -- Database.MySQLDatabase
Backend.Models -- Backend.Repositories


@enduml
